-- ============================================================================
-- feishu-bot-proxy 建表脚本（单一来源）
--
-- 应用启动不再自动建表，部署前先对目标库（Supabase / 任意 Postgres）执行本文件：
--     psql "$DATABASE_URL" -f db/schema.sql
--
-- 全部使用 CREATE TABLE IF NOT EXISTS，重复执行是安全的。
-- 「历史升级」一节里的 ALTER 只对早于该功能创建的旧库需要，新库可忽略。
-- ============================================================================

-- ---------------------------------------------------------------------------
-- 消息留档：每次带请求体的调用写一行，无论成败，只追加、不清理。
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS message_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at BIGINT NOT NULL,
    create_datetime TEXT,             -- created_at 的可读形式，纯展示；旧行该列为 NULL
    bot_keys TEXT NOT NULL,           -- 复数形态：广播时代的旧行可能含多个逗号分隔的目标
    msg_type TEXT,
    title TEXT,
    text_preview TEXT,
    body TEXT NOT NULL,
    body_bytes INTEGER NOT NULL,
    client_ip TEXT,
    success INTEGER NOT NULL,         -- 0/1，仅当每个目标都接受才为 1
    code INTEGER NOT NULL,
    msg TEXT,
    results TEXT,                     -- JSON 数组文本
    stat_date TEXT,                   -- 战报自称的日期，取自标题，不是落库时间
    survival_level BIGINT,            -- 生存等级，原值（写入走 setLong，故用 BIGINT）
    exp_gained BIGINT,                -- 本次新增的生存经验（与上一条战报的差分）
    bp_gained BIGINT,                 -- 本次新增的 BP
    duration TEXT                     -- 本次新增的对局时长 HH:MM:SS，赛季重置时为负数
);

-- ---------------------------------------------------------------------------
-- 机器人定义。feishu.bots 只作首次启动种子，此后以数据库为准。
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS bot (
    bot_key TEXT PRIMARY KEY,
    webhook TEXT NOT NULL,
    secret TEXT NOT NULL DEFAULT '',
    enabled INTEGER NOT NULL DEFAULT 1,
    keywords TEXT NOT NULL DEFAULT '',   -- 逗号连接
    created_at BIGINT NOT NULL,
    updated_at BIGINT NOT NULL
);

-- ---------------------------------------------------------------------------
-- 应用级键值设置（目前只有 default-bot 一项）。
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS app_setting (
    setting_key TEXT PRIMARY KEY,
    setting_value TEXT NOT NULL
);

-- ---------------------------------------------------------------------------
-- 存活告警规则。
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS alert_rule (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bot_key TEXT NOT NULL,
    threshold_minutes INTEGER NOT NULL,
    cooldown_minutes INTEGER NOT NULL,
    enabled INTEGER NOT NULL DEFAULT 1,
    alert_bot_key TEXT NOT NULL,
    last_alert_at BIGINT,             -- null = 当前未处于告警态
    created_at BIGINT NOT NULL,
    updated_at BIGINT NOT NULL
);

-- ---------------------------------------------------------------------------
-- 告警调度执行日志。每分钟追加一行，只追加、不清理。
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS alert_run_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    executed_at BIGINT NOT NULL,
    status TEXT NOT NULL,
    rules_scanned INTEGER NOT NULL,
    alerts_fired INTEGER NOT NULL,
    duration_ms BIGINT NOT NULL,
    detail TEXT
);

-- ---------------------------------------------------------------------------
-- 封禁查询记录。每次查询（成功或失败）追加一行，只追加、不清理。
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS ban_check_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    player TEXT NOT NULL,
    platform TEXT NOT NULL,
    success INTEGER NOT NULL,         -- 0/1
    ban_status TEXT,
    ban_type TEXT,
    match_count BIGINT,
    total_matches BIGINT,
    level TEXT,
    site_uuid TEXT,
    error TEXT,
    queried_at BIGINT NOT NULL,
    queried_datetime TEXT
);

-- ---------------------------------------------------------------------------
-- 「我的账号」。account_id 即玩家昵称（主键）。
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS account (
    account_id TEXT PRIMARY KEY,
    ban_status TEXT NOT NULL DEFAULT '正常',
    level TEXT,
    platform TEXT,                      -- 平台：steam / kakao / console / xbox / psn；旧行 NULL 按 steam 处理
    last_checked_at TEXT,
    total_matches BIGINT
);

-- ============================================================================
-- 历史升级（仅早于该功能创建的旧库需要；新库已由上面的 CREATE TABLE 一次建全）
--
-- 旧库 message_log 缺这些后加列，按需逐条执行：
-- ============================================================================
-- ALTER TABLE message_log ADD COLUMN stat_date TEXT;
-- ALTER TABLE message_log ADD COLUMN survival_level BIGINT;
-- ALTER TABLE message_log ADD COLUMN exp_gained BIGINT;
-- ALTER TABLE message_log ADD COLUMN bp_gained BIGINT;
-- ALTER TABLE message_log ADD COLUMN duration TEXT;
-- ALTER TABLE message_log ADD COLUMN create_datetime TEXT;
-- ALTER TABLE account ADD COLUMN platform TEXT;   -- 已有 account 库补平台列（新库已含）
