package com.example.feishuproxy.store;

import com.example.feishuproxy.config.FeishuProperties;
import com.example.feishuproxy.model.AlertRule;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.stereotype.Component;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.List;

/**
 * 告警规则的后端存储，与 {@link BotRepository} 共用同一套 {@code feishu.store.*} 连接（Supabase 同一个库）。
 * 告警规则是低频配置——只在后台增删改和调度器每轮检查时读写，所以<b>每次操作独立开连接</b>，
 * 复用 {@code BotRepository} 那套「读失败返回 null、写失败抛 {@link IllegalStateException}」的语义约定。
 */
@Component
public class AlertRuleRepository {

    private static final Logger log = LoggerFactory.getLogger(AlertRuleRepository.class);

    private static final String DDL =
            "CREATE TABLE IF NOT EXISTS alert_rule ("
                    + "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,"
                    + "bot_key TEXT NOT NULL,"
                    + "threshold_minutes INTEGER NOT NULL,"
                    + "cooldown_minutes INTEGER NOT NULL,"
                    + "enabled INTEGER NOT NULL DEFAULT 1,"
                    + "alert_bot_key TEXT NOT NULL,"
                    + "last_alert_at BIGINT,"
                    + "created_at BIGINT NOT NULL,"
                    + "updated_at BIGINT NOT NULL)";

    private static final String COLUMNS =
            "id, bot_key, threshold_minutes, cooldown_minutes, enabled, alert_bot_key,"
                    + " last_alert_at, created_at, updated_at";

    private final boolean configured;

    private final String jdbcUrl;
    private final String username;
    private final String password;

    public AlertRuleRepository(FeishuProperties properties) {
        this.jdbcUrl = properties.getStore().getJdbcUrl();
        this.username = properties.getStore().getUsername();
        this.password = properties.getStore().getPassword();
        this.configured = jdbcUrl != null && !jdbcUrl.trim().isEmpty();
        if (!configured) {
            log.info("alert rule store disabled: no jdbc-url configured");
            return;
        }
        try (Connection connection = open();
             Statement statement = connection.createStatement()) {
            statement.execute(DDL);
        } catch (SQLException e) {
            // 与 BotRepository 一致：建表失败只降级，不阻断启动。调度器读到 null 会自动跳过。
            log.warn("alert rule store unavailable at startup; rules stay empty until a reload", e);
        }
    }

    /** 全部规则，按 id 升序。数据库不可用（或未配置）时返回 {@code null}。 */
    public List<AlertRule> findAll() {
        if (!configured) {
            return null;
        }
        try (Connection connection = open();
             Statement statement = connection.createStatement();
             ResultSet rs = statement.executeQuery("SELECT " + COLUMNS + " FROM alert_rule ORDER BY id")) {
            List<AlertRule> out = new ArrayList<>();
            while (rs.next()) {
                out.add(read(rs));
            }
            return out;
        } catch (SQLException e) {
            log.warn("failed to load alert rules", e);
            return null;
        }
    }

    /** 单条规则。数据库不可用时抛异常；不存在时返回 {@code null}。 */
    public AlertRule find(long id) {
        requireConfigured();
        try (Connection connection = open()) {
            try (PreparedStatement statement = connection.prepareStatement(
                    "SELECT " + COLUMNS + " FROM alert_rule WHERE id = ?")) {
                statement.setLong(1, id);
                try (ResultSet rs = statement.executeQuery()) {
                    return rs.next() ? read(rs) : null;
                }
            }
        } catch (SQLException e) {
            throw storeUnavailable(e);
        }
    }

    /** 新增一条规则，返回自增主键。 */
    public long insert(AlertRule rule) {
        requireConfigured();
        long now = System.currentTimeMillis();
        try (Connection connection = open()) {
            try (PreparedStatement statement = connection.prepareStatement(
                    "INSERT INTO alert_rule (bot_key, threshold_minutes, cooldown_minutes, enabled,"
                            + " alert_bot_key, last_alert_at, created_at, updated_at)"
                            + " VALUES (?,?,?,?,?,?,?,?)",
                    Statement.RETURN_GENERATED_KEYS)) {
                statement.setString(1, rule.getBotKey());
                statement.setInt(2, rule.getThresholdMinutes());
                statement.setInt(3, rule.getCooldownMinutes());
                statement.setInt(4, rule.isEnabled() ? 1 : 0);
                statement.setString(5, rule.getAlertBotKey());
                setNullable(statement, 6, rule.getLastAlertAt());
                statement.setLong(7, now);
                statement.setLong(8, now);
                statement.executeUpdate();
                try (ResultSet keys = statement.getGeneratedKeys()) {
                    return keys.next() ? keys.getLong(1) : 0L;
                }
            }
        } catch (SQLException e) {
            throw storeUnavailable(e);
        }
    }

    /** 更新一条规则的配置项（不含 {@code last_alert_at}，那列由调度器单独维护）。 */
    public void update(AlertRule rule) {
        requireConfigured();
        try (Connection connection = open()) {
            try (PreparedStatement statement = connection.prepareStatement(
                    "UPDATE alert_rule SET bot_key = ?, threshold_minutes = ?, cooldown_minutes = ?,"
                            + " enabled = ?, alert_bot_key = ?, updated_at = ? WHERE id = ?")) {
                statement.setString(1, rule.getBotKey());
                statement.setInt(2, rule.getThresholdMinutes());
                statement.setInt(3, rule.getCooldownMinutes());
                statement.setInt(4, rule.isEnabled() ? 1 : 0);
                statement.setString(5, rule.getAlertBotKey());
                statement.setLong(6, System.currentTimeMillis());
                statement.setLong(7, rule.getId());
                statement.executeUpdate();
            }
        } catch (SQLException e) {
            throw storeUnavailable(e);
        }
    }

    public void delete(long id) {
        requireConfigured();
        try (Connection connection = open()) {
            try (PreparedStatement statement = connection.prepareStatement(
                    "DELETE FROM alert_rule WHERE id = ?")) {
                statement.setLong(1, id);
                statement.executeUpdate();
            }
        } catch (SQLException e) {
            throw storeUnavailable(e);
        }
    }

    /** 记录一次告警发出（或重置为 null，表示恢复）。由调度器维护，不经过 update()。 */
    public void setLastAlertAt(long id, Long epochMillis) {
        requireConfigured();
        try (Connection connection = open()) {
            try (PreparedStatement statement = connection.prepareStatement(
                    "UPDATE alert_rule SET last_alert_at = ?, updated_at = ? WHERE id = ?")) {
                setNullable(statement, 1, epochMillis);
                statement.setLong(2, System.currentTimeMillis());
                statement.setLong(3, id);
                statement.executeUpdate();
            }
        } catch (SQLException e) {
            throw storeUnavailable(e);
        }
    }

    private static AlertRule read(ResultSet rs) throws SQLException {
        AlertRule rule = new AlertRule();
        rule.setId(rs.getLong("id"));
        rule.setBotKey(rs.getString("bot_key"));
        rule.setThresholdMinutes(rs.getInt("threshold_minutes"));
        rule.setCooldownMinutes(rs.getInt("cooldown_minutes"));
        rule.setEnabled(rs.getInt("enabled") != 0);
        rule.setAlertBotKey(rs.getString("alert_bot_key"));
        rule.setLastAlertAt(nullableLong(rs, "last_alert_at"));
        rule.setCreatedAt(rs.getLong("created_at"));
        rule.setUpdatedAt(rs.getLong("updated_at"));
        return rule;
    }

    private static void setNullable(PreparedStatement statement, int index, Long value) throws SQLException {
        if (value == null) {
            statement.setNull(index, java.sql.Types.BIGINT);
        } else {
            statement.setLong(index, value);
        }
    }

    private static Long nullableLong(ResultSet rs, String column) throws SQLException {
        long value = rs.getLong(column);
        return rs.wasNull() ? null : value;
    }

    private Connection open() throws SQLException {
        return DriverManager.getConnection(jdbcUrl, username, password);
    }

    private void requireConfigured() {
        if (!configured) {
            throw new IllegalStateException("alert rule store not configured");
        }
    }

    private static IllegalStateException storeUnavailable(SQLException e) {
        return new IllegalStateException("alert rule store unavailable", e);
    }
}
