package com.example.feishuproxy.store;

import com.example.feishuproxy.config.FeishuProperties;
import com.example.feishuproxy.model.AlertRunLog;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.stereotype.Component;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.List;

/**
 * 告警调度执行日志的后端存储，与 {@link AlertRuleRepository} 共用同一套 {@code feishu.store.*} 连接。
 * 每分钟追加一行、低频查询，所以<b>每次操作独立开连接</b>，复用「读失败返回 null、写失败抛
 * {@link IllegalStateException}」的语义约定。表只追加、不清理。
 */
@Component
public class AlertRunLogRepository {

    private static final Logger log = LoggerFactory.getLogger(AlertRunLogRepository.class);

    private static final String DDL =
            "CREATE TABLE IF NOT EXISTS alert_run_log ("
                    + "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,"
                    + "executed_at BIGINT NOT NULL,"
                    + "status TEXT NOT NULL,"
                    + "rules_scanned INTEGER NOT NULL,"
                    + "alerts_fired INTEGER NOT NULL,"
                    + "duration_ms BIGINT NOT NULL,"
                    + "detail TEXT)";

    private static final String COLUMNS =
            "id, executed_at, status, rules_scanned, alerts_fired, duration_ms, detail";

    /** 单页上限，避免过大的 limit 把整张表拉进内存。 */
    public static final int MAX_PAGE = 200;

    private final boolean configured;

    private final String jdbcUrl;
    private final String username;
    private final String password;

    public AlertRunLogRepository(FeishuProperties properties) {
        this.jdbcUrl = properties.getStore().getJdbcUrl();
        this.username = properties.getStore().getUsername();
        this.password = properties.getStore().getPassword();
        this.configured = jdbcUrl != null && !jdbcUrl.trim().isEmpty();
        if (!configured) {
            log.info("alert run log store disabled: no jdbc-url configured");
            return;
        }
        try (Connection connection = open();
             Statement statement = connection.createStatement()) {
            statement.execute(DDL);
        } catch (SQLException e) {
            log.warn("alert run log store unavailable at startup; runs won't be persisted until a reload", e);
        }
    }

    /** 追加一行执行日志。写失败抛 {@link IllegalStateException}（由调度器静默捕获）。 */
    public void insert(AlertRunLog logEntry) {
        requireConfigured();
        try (Connection connection = open()) {
            try (PreparedStatement statement = connection.prepareStatement(
                    "INSERT INTO alert_run_log (executed_at, status, rules_scanned, alerts_fired,"
                            + " duration_ms, detail) VALUES (?,?,?,?,?,?)")) {
                statement.setLong(1, logEntry.getExecutedAt());
                statement.setString(2, logEntry.getStatus());
                statement.setInt(3, logEntry.getRulesScanned());
                statement.setInt(4, logEntry.getAlertsFired());
                statement.setLong(5, logEntry.getDurationMs());
                statement.setString(6, logEntry.getDetail());
                statement.executeUpdate();
            }
        } catch (SQLException e) {
            throw storeUnavailable(e);
        }
    }

    /** 最新在前。数据库不可用（或未配置）时返回 {@code null}。 */
    public List<AlertRunLog> query(int limit, int offset) {
        if (!configured) {
            return null;
        }
        List<AlertRunLog> out = new ArrayList<>();
        try (Connection connection = open()) {
            try (PreparedStatement statement = connection.prepareStatement(
                    "SELECT " + COLUMNS + " FROM alert_run_log ORDER BY id DESC LIMIT ? OFFSET ?")) {
                statement.setInt(1, Math.max(1, Math.min(limit, MAX_PAGE)));
                statement.setInt(2, Math.max(0, offset));
                try (ResultSet rs = statement.executeQuery()) {
                    while (rs.next()) {
                        out.add(read(rs));
                    }
                }
            }
            return out;
        } catch (SQLException e) {
            log.warn("failed to query alert run log", e);
            return null;
        }
    }

    /** 全表行数；数据库不可用（或未配置）时返回 0。表只追加，COUNT 开销可忽略。 */
    public long total() {
        if (!configured) {
            return 0L;
        }
        try (Connection connection = open();
             Statement statement = connection.createStatement();
             ResultSet rs = statement.executeQuery("SELECT COUNT(*) FROM alert_run_log")) {
            return rs.next() ? rs.getLong(1) : 0L;
        } catch (SQLException e) {
            log.warn("failed to count alert run log", e);
            return 0L;
        }
    }

    private static AlertRunLog read(ResultSet rs) throws SQLException {
        AlertRunLog logEntry = new AlertRunLog();
        logEntry.setId(rs.getLong("id"));
        logEntry.setExecutedAt(rs.getLong("executed_at"));
        logEntry.setStatus(rs.getString("status"));
        logEntry.setRulesScanned(rs.getInt("rules_scanned"));
        logEntry.setAlertsFired(rs.getInt("alerts_fired"));
        logEntry.setDurationMs(rs.getLong("duration_ms"));
        logEntry.setDetail(rs.getString("detail"));
        return logEntry;
    }

    private Connection open() throws SQLException {
        return DriverManager.getConnection(jdbcUrl, username, password);
    }

    private void requireConfigured() {
        if (!configured) {
            throw new IllegalStateException("alert run log store not configured");
        }
    }

    private static IllegalStateException storeUnavailable(SQLException e) {
        return new IllegalStateException("alert run log store unavailable", e);
    }
}
