package com.example.feishuproxy.store;

import com.example.feishuproxy.config.FeishuProperties;
import com.example.feishuproxy.model.BanCheckLog;
import com.example.feishuproxy.model.BanCheckResult;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.stereotype.Component;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.Types;
import java.util.ArrayList;
import java.util.List;

/**
 * 封禁查询记录的后端存储：每次封禁查询（成功或失败）追加一行到 {@code ban_check_log}，
 * 与 {@link AlertRunLogRepository} 共用同一套 {@code feishu.store.*} 连接。
 * <p>
 * 记录只是查询的旁路，绝不能影响查询应答——所以 {@link #record} 尽力而为，失败只记日志、
 * 不抛异常；查询与计数沿用「读失败返回 null、计数返回 0」的语义约定。表只追加、不清理。
 */
@Component
public class BanCheckLogRepository {

    private static final Logger log = LoggerFactory.getLogger(BanCheckLogRepository.class);

    private static final String DDL =
            "CREATE TABLE IF NOT EXISTS ban_check_log ("
                    + "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,"
                    + "player TEXT NOT NULL,"
                    + "platform TEXT NOT NULL,"
                    + "success INTEGER NOT NULL,"
                    + "ban_status TEXT,"
                    + "ban_type TEXT,"
                    + "match_count BIGINT,"
                    + "total_matches BIGINT,"
                    + "level TEXT,"
                    + "site_uuid TEXT,"
                    + "error TEXT,"
                    + "queried_at BIGINT NOT NULL,"
                    + "queried_datetime TEXT)";

    private static final String COLUMNS =
            "id, player, platform, success, ban_status, ban_type, match_count, total_matches, level,"
                    + " site_uuid, error, queried_at, queried_datetime";

    private static final String INSERT =
            "INSERT INTO ban_check_log (player, platform, success, ban_status, ban_type, match_count,"
                    + " total_matches, level, site_uuid, error, queried_at, queried_datetime)"
                    + " VALUES (?,?,?,?,?,?,?,?,?,?,?,?)";

    /** 单页上限，避免过大的 limit 把整张表拉进内存。 */
    public static final int MAX_PAGE = 200;

    private final boolean configured;

    private final String jdbcUrl;
    private final String username;
    private final String password;

    public BanCheckLogRepository(FeishuProperties properties) {
        this.jdbcUrl = properties.getStore().getJdbcUrl();
        this.username = properties.getStore().getUsername();
        this.password = properties.getStore().getPassword();
        this.configured = jdbcUrl != null && !jdbcUrl.trim().isEmpty();
        if (!configured) {
            log.info("ban check log store disabled: no jdbc-url configured");
            return;
        }
        try (Connection connection = open();
             Statement statement = connection.createStatement()) {
            statement.execute(DDL);
        } catch (SQLException e) {
            log.warn("ban check log store unavailable at startup; checks won't be persisted until a reload", e);
        }
    }

    /**
     * 追加一行查询记录，成功失败都写。绝不抛异常——记录失败不能改变已经答复给查询方的结果。
     *
     * @param player   查询的玩家昵称（已 trim）
     * @param platform 平台，如 steam / kakao
     * @param result   本次查询的结果
     */
    public void record(String player, String platform, BanCheckResult result) {
        if (!configured) {
            return;
        }
        try {
            insert(player, platform, result);
        } catch (Exception e) {
            log.warn("failed to persist ban check log (player={} platform={})", player, platform, e);
        }
    }

    private void insert(String player, String platform, BanCheckResult result) throws SQLException {
        long now = System.currentTimeMillis();
        try (Connection connection = open();
             PreparedStatement statement = connection.prepareStatement(INSERT)) {
            statement.setString(1, player);
            statement.setString(2, platform);
            statement.setInt(3, result.isSuccess() ? 1 : 0);
            statement.setString(4, result.isSuccess() ? result.getBanStatus() : null);
            statement.setString(5, result.isSuccess() ? result.getBanType() : null);
            setNullable(statement, 6, result.isSuccess() ? result.getMatchCount() : null);
            setNullable(statement, 7, result.isSuccess() ? result.getTotalMatches() : null);
            statement.setString(8, result.isSuccess() ? result.getLevelText() : null);
            statement.setString(9, result.isSuccess() ? result.getSiteUUID() : null);
            statement.setString(10, result.isSuccess() ? null : result.getError());
            statement.setLong(11, now);
            statement.setString(12, BanCheckLog.format(now));
            statement.executeUpdate();
        }
    }

    /** 最新在前。数据库不可用（或未配置）时返回 {@code null}。 */
    public List<BanCheckLog> query(int limit, int offset) {
        if (!configured) {
            return null;
        }
        List<BanCheckLog> out = new ArrayList<>();
        try (Connection connection = open()) {
            try (PreparedStatement statement = connection.prepareStatement(
                    "SELECT " + COLUMNS + " FROM ban_check_log ORDER BY id DESC LIMIT ? OFFSET ?")) {
                statement.setInt(1, Math.max(1, Math.min(limit, MAX_PAGE)));
                statement.setInt(2, Math.max(0, offset));
                try (ResultSet rs = statement.executeQuery()) {
                    while (rs.next()) {
                        out.add(read(rs));
                    }
                }
            }
            return out;
        } catch (SQLException e) {
            log.warn("failed to query ban check log", e);
            return null;
        }
    }

    /** 全表行数；数据库不可用（或未配置）时返回 0。表只追加，COUNT 开销可忽略。 */
    public long total() {
        if (!configured) {
            return 0L;
        }
        try (Connection connection = open();
             Statement statement = connection.createStatement();
             ResultSet rs = statement.executeQuery("SELECT COUNT(*) FROM ban_check_log")) {
            return rs.next() ? rs.getLong(1) : 0L;
        } catch (SQLException e) {
            log.warn("failed to count ban check log", e);
            return 0L;
        }
    }

    private static BanCheckLog read(ResultSet rs) throws SQLException {
        BanCheckLog record = new BanCheckLog();
        record.setId(rs.getLong("id"));
        record.setPlayer(rs.getString("player"));
        record.setPlatform(rs.getString("platform"));
        record.setSuccess(rs.getInt("success") != 0);
        record.setBanStatus(rs.getString("ban_status"));
        record.setBanType(rs.getString("ban_type"));
        record.setMatchCount(nullableLong(rs, "match_count"));
        record.setTotalMatches(nullableLong(rs, "total_matches"));
        record.setLevel(rs.getString("level"));
        record.setSiteUuid(rs.getString("site_uuid"));
        record.setError(rs.getString("error"));
        record.setQueriedAt(rs.getLong("queried_at"));
        record.setQueriedDatetime(rs.getString("queried_datetime"));
        return record;
    }

    private static void setNullable(PreparedStatement statement, int index, Integer value) throws SQLException {
        if (value == null) {
            statement.setNull(index, Types.BIGINT);
        } else {
            statement.setLong(index, value.longValue());
        }
    }

    private static Long nullableLong(ResultSet rs, String column) throws SQLException {
        long value = rs.getLong(column);
        return rs.wasNull() ? null : value;
    }

    private Connection open() throws SQLException {
        return DriverManager.getConnection(jdbcUrl, username, password);
    }
}